### PR TITLE
"email_verified" value cannot be compared to string 'true', it's retu…

### PR DESCRIPTION
**Pull request by maysam**
…rning false, it should be compared against value true

### CODE REVIEW

**Comment by dhh** [comment]
What's typecasting the string to a boolean?

**Comment by dhh** [comment]
Looks to me that we just get a json payload back with true as a string. Google's own example does a boolean typecast here: https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by maysam** [comment]
Actually it's working in production, but when I was inspecting in development console the  "email_verified" was set to true and not  "true"

**Comment by georgeclaghorn** [comment]
The OpenID spec indicates that the `email_verified` claim should have a boolean value, and I see Google returning a boolean:

```
..."email"=>"george@basecamp.com", "email_verified"=>true...
```

I’m not sure how the Java code example @dhh linked to works. `GoogleIdToken.Payload.getEmailVerified()` is documented as returning a `Boolean`, and there is no version of `Boolean.valueOf()` that (a) accepts a `Boolean` object rather than a string or a boolean primitive and (b) returns a boolean primitive. I suspect the example is wrong.

Thanks, @maysam! Sorry for the delay.

**Pull request merged**
